const barChartData = [
    { name: "Mombasa", individual: 18, organization: 10, all: 28 },
    { name: "Kwale", individual: 22, organization: 18, all: 40 },
    { name: "Kilifi", individual: 12, organization: 10, all: 22 },
    { name: "TRV", individual: 15, organization: 12, all: 27 },
    { name: "Lamu", individual: 10, organization: 8, all: 18 },
    { name: "Taita Taveta", individual: 20, organization: 15, all: 35 },
    { name: "Garissa", individual: 8, organization: 6, all: 14 },
    { name: "Wajir", individual: 12, organization: 10, all: 22 },
    { name: "Mandera", individual: 14, organization: 12, all: 26 },
    { name: "Marsabit", individual: 25, organization: 20, all: 45 },
    { name: "isiolo", individual: 18, organization: 15, all: 33 },
    { name: "Meru", individual: 20, organization: 18, all: 38 },
    { name: "Tharaka Nithi", individual: 22, organization: 20, all: 42 },
    { name: "Embu", individual: 15, organization: 12, all: 27 },
    { name: "Kitui", individual: 10, organization: 8, all: 18 },
    { name: "Machakos", individual: 12, organization: 10, all: 22 },
    { name: "Makueni", individual: 14, organization: 12, all: 26 },
    { name: "Nyandarua", individual: 18, organization: 15, all: 33 },
    { name: "Nyeri", individual: 22, organization: 20, all: 42 },
    { name: "Kirinyaga", individual: 15, organization: 12, all: 27 },
    { name: "Murang'a", individual: 10, organization: 8, all: 18 },
    { name: "Kiambu", individual: 12, organization: 10, all: 22 },
    { name: "Turkana", individual: 14, organization: 12, all: 26 },
    { name: "West Pokot", individual: 18, organization: 15, all: 33 },
    { name: "Samburu", individual: 22, organization: 20, all: 42 },
    { name: "Trans-Nzoia", individual: 15, organization: 12, all: 27 },
    { name: "Uasin Gishu", individual: 10, organization: 8, all: 18 },
    { name: "Elgeyo Marakwet", individual: 12, organization: 10, all: 22 },
    { name: "Nandi", individual: 14, organization:  10, all: 24 },
    { name: "Baringo", individual: 18, organization:  10, all: 28 },
    { name: "Laikipia", individual: 22, organization:  15, all: 37 },
    { name: "Nakuru", individual: 15, organization:  10, all: 25 },
    { name: "Narok", individual: 10, organization: 5, all: 15 },
    { name: "Kajiado", individual: 12, organization:  8, all: 20 },
    { name: "Bomet", individual: 14, organization:  10, all: 24 },
    { name: "Kericho", individual: 18, organization:  10, all: 28 },
    { name: "Bungoma", individual: 22, organization:  15, all: 37 },
    { name: "Busia", individual: 15, organization:  10, all: 25 },
    { name: "Vihiga", individual: 10, organization: 5, all: 15 },
    { name: "Kakamega", individual: 12, organization:  8, all: 20 },
    { name: "Siaya", individual: 14, organization:  10, all: 24 },
    { name: "Homa Bay", individual: 18, organization:  10, all: 28 },
    { name: "Migori", individual: 22, organization:  15, all: 37 },
    { name: "Kisi", individual: 15, organization:  10, all: 25 },
    { name: "Nyamira", individual: 10, organization: 5, all: 15 },
    { name: "Nairobi", individual: 12, organization:  8, all: 20 },
    { name: "Kisumu", individual: 14, organization:  10, all: 24 },
];

export default barChartData;