const barChartBuildersData = [
    { name: "Mombasa", Fundis: 18, Professionals: 10, Contractors: 28, Hardware: 15 },
    { name: "Kwale", Fundis: 22, Professionals: 18, Contractors: 40, Hardware: 32 },
    { name: "Kilifi", Fundis: 12, Professionals: 10, Contractors: 22, Hardware: 23 },
    { name: "TRV", Fundis: 15, Professionals: 12, Contractors: 27, Hardware: 33 },
    { name: "Lamu", Fundis: 10, Professionals: 8, Contractors: 18, Hardware: 12 },
    { name: "Taita Taveta", Fundis: 20, Professionals: 15, Contractors: 35, Hardware: 20 },
    { name: "Garissa", Fundis: 8, Professionals: 6, Contractors: 14, Hardware: 10 },
    { name: "Wajir", Fundis: 12, Professionals: 10, Contractors: 22, Hardware: 25 },
    { name: "Mandera", Fundis: 14, Professionals: 12, Contractors: 26, Hardware: 30},
    { name: "Marsabit", Fundis: 25, Professionals: 20, Contractors: 45, Hardware: 50 },
    { name: "isiolo", Fundis: 18, Professionals: 15, Contractors: 33, Hardware: 60 },
    { name: "Meru", Fundis: 20, Professionals: 18, Contractors: 38, Hardware: 45 },
    { name: "Tharaka Nithi", Fundis: 22, Professionals: 20, Contractors: 42, Hardware: 55 },
    { name: "Embu", Fundis: 15, Professionals: 12, Contractors: 27, Hardware: 35 },
    { name: "Kitui", Fundis: 10, Professionals: 8, Contractors: 18, Hardware: 20 },
    { name: "Machakos", Fundis: 12, Professionals: 10, Contractors: 22, Hardware: 30 },
    { name: "Makueni", Fundis: 14, Professionals: 12, Contractors: 26, Hardware: 40 },
    { name: "Nyandarua", Fundis: 18, Professionals: 15, Contractors: 33, Hardware: 43 },
    { name: "Nyeri", Fundis: 22, Professionals: 20, Contractors: 42, Hardware: 50 },
    { name: "Kirinyaga", Fundis: 15, Professionals: 12, Contractors: 27, Hardware: 35 },
    { name: "Murang'a", Fundis: 10, Professionals: 8, Contractors: 18, Hardware: 25 },
    { name: "Kiambu", Fundis: 12, Professionals: 10, Contractors: 22, Hardware: 30 },
    { name: "Turkana", Fundis: 14, Professionals: 12, Contractors: 26, Hardware: 38 },
    { name: "West Pokot", Fundis: 18, Professionals: 15, Contractors: 33, Hardware: 45 },
    { name: "Samburu", Fundis: 22, Professionals: 20, Contractors: 42, Hardware: 50 },
    { name: "Trans-Nzoia", Fundis: 15, Professionals: 12, Contractors: 27, Hardware: 35 },
    { name: "Uasin Gishu", Fundis: 10, Professionals: 8, Contractors: 18, Hardware: 20 },
    { name: "Elgeyo Marakwet", Fundis: 12, Professionals: 10, Contractors: 22, Hardware: 30 },
    { name: "Nandi", Fundis: 14, Professionals:  10, Contractors: 24, Hardware: 32 },
    { name: "Baringo", Fundis: 18, Professionals:  10, Contractors: 28, Hardware: 40 },
    { name: "Laikipia", Fundis: 22, Professionals:  15, Contractors: 37, Hardware: 45 },
    { name: "Nakuru", Fundis: 15, Professionals:  10, Contractors: 25, Hardware: 30 },
    { name: "Narok", Fundis: 10, Professionals: 5, Contractors: 15, Hardware: 20 },
    { name: "Kajiado", Fundis: 12, Professionals:  8, Contractors: 20, Hardware: 25 },
    { name: "Bomet", Fundis: 14, Professionals:  10, Contractors: 24, Hardware: 30 },
    { name: "Kericho", Fundis: 18, Professionals:  10, Contractors: 28, Hardware: 35 },
    { name: "Bungoma", Fundis: 22, Professionals:  15, Contractors: 37, Hardware: 45 },
    { name: "Busia", Fundis: 15, Professionals:  10, Contractors: 25, Hardware: 30 },
    { name: "Vihiga", Fundis: 10, Professionals: 5, Contractors: 15, Hardware: 20 },
    { name: "Kakamega", Fundis: 12, Professionals:  8, Contractors: 20, Hardware: 25 },
    { name: "Siaya", Fundis: 14, Professionals:  10, Contractors: 24, Hardware: 30 },
    { name: "Homa Bay", Fundis: 18, Professionals:  10, Contractors: 28, Hardware: 33 },
    { name: "Migori", Fundis: 22, Professionals:  15, Contractors: 37, Hardware: 40 },
    { name: "Kisi", Fundis: 15, Professionals:  10, Contractors: 25, Hardware: 30 },
    { name: "Nyamira", Fundis: 10, Professionals: 5, Contractors: 15, Hardware: 20 },
    { name: "Nairobi", Fundis: 12, Professionals:  8, Contractors: 20, Hardware: 25 },
    { name: "Kisumu", Fundis: 14, Professionals:  10, Contractors: 24, Hardware: 30 },
];

export default barChartBuildersData;